services:

  postgres:
    image: postgres:latest
    ports:
      - "5433:5432"
    networks:
      - my-network
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data


  mongodb:
    image: "mongo:latest"
    volumes:
      - ./data:/data/db
    networks:
      - my-network

  backend:
    build:
      context: .          
      dockerfile: Dockerfile  
    ports:
      - "8000:8000"
    networks:
      - my-network    
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
    env_file:
      - .env
    depends_on:
      - postgres

  web:
    build:
      context: ./web    
      dockerfile: Dockerfile  
    ports:
      - "3000:3000"
    networks:
      - my-network  
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  my-network  :
    driver: bridge

volumes:
  postgres_data:
    driver: local
  mongo_data:
    driver: local
 